version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-{{checksum "mix.lock"}}
      - run: git submodule sync
      - run: git submodule update --init
      - run: sudo apt-get install libblas-dev
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
      - run: mix credo --strict -i todo
      #- run: mix dogma
      - run: mix dialyzer --halt-exit-status
      - save_cache:
          key: build-{{checksum "mix.lock"}}
          paths:
            - deps
            - _build
